// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";
import path from "path";

// Load from .env.local if it exists (local development)
// Otherwise use environment variables (Docker/production)
if (process.env.NODE_ENV !== "production") {
  config({ path: path.resolve(__dirname, ".env.local") });
} else {
  config({ path: path.resolve(__dirname, ".env") });
}

const databaseUrl = process.env.DATABASE_URL;

if (!databaseUrl) {
  throw new Error("DATABASE_URL environment variable is not set");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});

