// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";
import path from "path";

// Load environment variables from .env
config({ path: path.resolve(__dirname, ".env") });

const databaseUrl = process.env.DATABASE_URL;
// Use DIRECT_URL for migrations (Supabase requires direct connection, not pooler)
const directUrl = process.env.DIRECT_URL;

// For build stage, allow DATABASE_URL from environment (set in Dockerfile)
if (!databaseUrl) {
  throw new Error("DATABASE_URL environment variable is not set");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use DIRECT_URL for migrations if available, otherwise fallback to DATABASE_URL
    url: directUrl || databaseUrl,
  },
});

